apiVersion: apps/v1
kind: Deployment
metadata:
  name: guardx-auth
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: guardx-auth
  template:
    metadata:
      labels:
        app: guardx-auth
    spec:
      containers:
        - name: guardx-auth
          image: guardx-auth:1.0
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: dev-secrets
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: dev-secrets
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dev-secrets
                  key: SPRING_DATASOURCE_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: dev-secrets
                  key: JWT_SECRET
