apiVersion: v1
kind: Service
metadata:
  name: guardx-auth-service
  namespace: dev
spec:
  selector:
    app: guardx-auth
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: NodePort
